apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aceest
    spec:
      containers:
      - name: aceest
        image: your-dockerhub-username/aceest_fitness:latest
        ports:
        - containerPort: 5000
